Sense_To_Label = {
                        'EntRel': 18,
                        'Expansion.Alternative': 10,
                        'Expansion': 17,
                        'Temporal.Asynchronous.Precedence': 0,
                        'Expansion.Instantiation': 1,
                        'Expansion.Restatement': 3,
                        'Contingency.Condition': 5,
                        'Temporal.Synchrony': 6,
                        'Comparison.Contrast': 7,
                        'Expansion.Conjunction': 8,
                        'Contingency.Cause.Result': 9,
                        'Comparison': 19,
                        'Expansion.Alternative.Chosen alternative': 11,
                        'Temporal.Asynchronous.Succession': 12,
                        'Contingency.Cause': 13,
                        'Expansion.Exception': 14,
                        'Contingency.Cause.Reason': 15,
                        'Contingency': 16,
                        'Temporal': 4,
                        'Comparison.Concession': 2}

Label_To_Sense = {
                        0: 'Temporal.Asynchronous.Precedence',
                        1: 'Expansion.Instantiation',
                        2: 'Comparison.Concession',
                        3: 'Expansion.Restatement',
                        4: 'Temporal',
                        5: 'Contingency.Condition',
                        6: 'Temporal.Synchrony',
                        7: 'Comparison.Contrast',
                        8: 'Expansion.Conjunction',
                        9: 'Contingency.Cause.Result',
                        10: 'Expansion.Alternative',
                        11: 'Expansion.Alternative.Chosen alternative',
                        12: 'Temporal.Asynchronous.Succession',
                        13: 'Contingency.Cause',
                        14: 'Expansion.Exception',
                        15: 'Contingency.Cause.Reason',
                        16: 'Contingency',
                        17: 'Expansion',
                        18: 'EntRel',
                        19: 'Comparison'}

Type_To_Label = {     'Comparison':0,
                      'Comparison.Contrast': 0,
                      'Comparison.Concession': 0,
                      'Contingency.Cause': 1,
                      'Contingency.Pragmatic cause': 1,
                      'Contingency.Condition': 1,
                      'Contingency.Cause.Result': 1,
                      'Contingency.Cause.Reason': 1,
                      'Contingency':1 ,
                      'Expansion.List': 2,
                      'Expansion.Alternative': 2,
                      'Expansion.Conjunction': 2,
                      'Expansion.Instantiation': 2,
                      'Expansion.Restatement': 2,
                      'Expansion.Exception': 2,
                      'Expansion.Alternative.Chosen alternative': 2,
                      'Expansion': 2,
                      'Temporal.Asynchronous': 3,
                      'Temporal.Synchrony': 3,
                      'Temporal.Asynchronous.Precedence': 3,
                      'Temporal.Asynchronous.Succession':3 ,
                      'Temporal': 3,
                      'EntRel': 4
                 }

